"use strict";

console.log("[Offsets] init");

const Offsets = {
    SCRIPT_CONTEXT_VTABLE: 0x23327C,
    SCRIPT_CONTEXT_DESCRIPTOR: 0x0033139C,

    INSTANCE_NAME: 0x24,
    INSTANCE_PARENT: 0x30,
    INSTANCE_CHILDREN: 0x28,
    INSTANCE_DESCRIPTOR: 0xC,
    
    DESCRIPTOR_NAME: 0x4,
    
    SCRIPT_CONTEXT_GLOBAL_STATE: 0x50,

    LUA_OBJECT_NEXT: 0x0,
    LUA_OBJECT_MARKED: 0x4,
    LUA_OBJECT_TT: 0x5,
    
    LUA_STATE_GT: 0x8,
    LUA_STATE_GLOBALS: 0x68,
    LUA_STATE_TOP: 0x10,
    LUA_STATE_BASE: 0x1C,
    
    GLOBAL_STATE_CKEY: 0x1C,
    GLOBAL_STATE_FREALLOC: 0x10,
    GLOBAL_STATE_USERDATA: 0xC,
    GLOBAL_STATE_ROOTGC: 0x30,
    GLOBAL_STATE_WHITE: 0x15,

    PROTO_P: 0x8,
    PROTO_SOURCE: 0xC,
    PROTO_LOCVARS: 0x10,
    PROTO_SIZEUPVALUES: 0x14,
    PROTO_CODE: 0x18,
    PROTO_SIZEK: 0x1C,
    PROTO_K: 0x20,
    PROTO_LINEINFO: 0x24,
    PROTO_UPVALUES: 0x28,
    PROTO_SIZEP: 0x2C,
    PROTO_SIZELOCVARS: 0x30,
    PROTO_SIZECODE: 0x34,
    PROTO_LINEDEFINED: 0x38,
    PROTO_GCLIST: 0x3C,
    PROTO_SIZELINEINFO: 0x40,
    PROTO_LASTLINEDEFINED: 0x44,
    PROTO_MAXSTACKSIZE: 0x48,
    PROTO_NUMPARAMS: 0x49,
    PROTO_NUPS: 0x4A,
    PROTO_IS_VARARG: 0x4B,

    CLOSURE_IS_C: 0x6,
    CLOSURE_NUPVALUES: 0x7,
    CLOSURE_GCLIST: 0x8,
    CLOSURE_ENV: 0xC,
    LCLOSURE_P: 0x10,
    LCLOSURE_UPVALS: 0x14
};